# A minimal Azure Pipelines build configuration file.
# This configuration has just a single stage,
# so we can skip the `stages` directive.

jobs:
- job: infrastructure
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: Npm@1
    inputs:
      command: install
      workingDir: "./"

  - task: PulumiAzRmTask@0
    inputs:
      azureSubscription: 'your-service-connection-name'
      command: "up"
      args: "--yes --skip-preview"
      cwd: "./"
      # Replace this with your values.
      stack: "<org-name>/<project-name>/<stack-name>"
